# Generated by Django 4.0.3 on 2022-03-13 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True, help_text='The time when the blog is created', verbose_name='Posted')),
                ('title', models.CharField(help_text="Blog's title", max_length=100)),
                ('content', models.TextField(help_text="Blog's content", max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Text of the comment', max_length=1000)),
                ('post_date', models.DateTimeField(auto_now_add=True, help_text='Time when comment was posted', verbose_name='Posted')),
                ('blog', models.ForeignKey(help_text='Blog being commented', on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('commenter', models.ForeignKey(help_text='The person commenting on the blog', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text="Author's biography", max_length=1000)),
                ('user', models.OneToOneField(help_text='User that is going to be an author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(help_text='Author of the blog', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogger'),
        ),
    ]
