# Generated by Django 4.0.3 on 2022-03-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-post_date',)},
        ),
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ('user__username',), 'permissions': [('can_approve_application', 'Can approve applications to be an author')]},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('post_date',)},
        ),
    ]
