# Generated by Django 4.0.3 on 2022-03-19 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_blogger_options_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(auto_now_add=True, help_text='The date when the application was sent for consideration'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('a', 'Accepted'), ('r', 'Rejected'), ('w', 'Awaiting')], default='w', help_text='Status of the application', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(help_text='User that wants to be an author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
