# Generated by Django 4.0.3 on 2022-03-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='The comment on why the application got this status', max_length=2000),
        ),
    ]
