# Generated by Django 4.0.3 on 2022-03-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_application_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bio',
            field=models.TextField(default='', help_text='Your biography', max_length=1000),
            preserve_default=False,
        ),
    ]
